# Generated by Django 3.2 on 2022-03-09 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=300)),
                ('value', models.CharField(blank=True, max_length=100)),
                ('decimel', models.CharField(blank=True, max_length=100)),
                ('unit', models.CharField(blank=True, max_length=10)),
                ('accession_no', models.CharField(blank=True, max_length=50)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('filing_date', models.DateField(blank=True, null=True)),
                ('form_type', models.CharField(choices=[('10-K', '10-K Filing'), ('10-Q', '10-Q Filing'), ('8-K', '8-K Filing'), ('YF', 'Yahoo Finance'), ('BB', 'Bloomberg'), ('OT', 'Other')], default='OT', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cik', models.CharField(blank=True, max_length=15)),
                ('name', models.CharField(max_length=50)),
                ('ticker', models.CharField(blank=True, max_length=200, null=True)),
                ('website', models.CharField(blank=True, max_length=200, null=True)),
                ('addresses', models.CharField(blank=True, max_length=500, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('sic', models.CharField(blank=True, max_length=6, null=True)),
                ('category', models.CharField(blank=True, max_length=150, null=True)),
                ('state_of_incorporation', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DerivedMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=100)),
                ('formula', models.CharField(blank=True, max_length=300)),
                ('form_type', models.CharField(choices=[('10-K', '10-K Filing'), ('10-Q', '10-Q Filing'), ('8-K', '8-K Filing'), ('YF', 'Yahoo Finance'), ('BB', 'Bloomberg'), ('OT', 'Other')], default='OT', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('filing_date', models.DateField(blank=True, null=True)),
                ('accession_no', models.CharField(blank=True, max_length=50)),
                ('unit', models.CharField(blank=True, max_length=10)),
                ('tag', models.CharField(max_length=300)),
                ('base_metrics', models.ManyToManyField(to='dashboard_api.BaseMetrics')),
                ('company', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard_api.companies')),
            ],
        ),
        migrations.AddField(
            model_name='basemetrics',
            name='company',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard_api.companies'),
        ),
    ]
