# Generated by Django 3.2 on 2022-03-14 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_api', '0003_basemetrics_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='derivedmetrics',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='derivedmetrics',
            name='value',
            field=models.FloatField(blank=True, max_length=100),
        ),
    ]
