# Generated by Django 3.2 on 2022-03-15 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_api', '0004_auto_20220314_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='founding_year',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='companies',
            name='overview',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='derivedmetrics',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
