# Generated by Django 3.2 on 2022-03-15 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_api', '0005_auto_20220315_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemetrics',
            name='value',
            field=models.FloatField(blank=True, max_length=100),
        ),
    ]
