# Generated by Django 3.2 on 2022-03-17 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_api', '0006_alter_basemetrics_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='derivedmetrics',
            name='score',
            field=models.FloatField(blank=True, default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='derivedmetrics',
            name='sentence',
            field=models.CharField(blank=True, max_length=1500),
        ),
        migrations.AddField(
            model_name='derivedmetrics',
            name='source',
            field=models.CharField(blank=True, default='xbrl', max_length=10),
        ),
        migrations.AlterField(
            model_name='basemetrics',
            name='source',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
