# Generated by Django 3.2 on 2022-03-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_api', '0008_auto_20220317_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='derivedmetrics',
            name='sentence_date',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
