# Generated by Django 4.0.3 on 2022-03-17 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_api', '0009_derivedmetrics_sentence_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filing_date', models.DateField(blank=True, null=True)),
                ('financial', models.FloatField(blank=True, max_length=100)),
                ('otheridiosyncracies', models.FloatField(blank=True, max_length=100)),
                ('legal', models.FloatField(blank=True, max_length=100)),
                ('othersystematic', models.FloatField(blank=True, max_length=100)),
                ('tax', models.FloatField(blank=True, max_length=100)),
                ('company', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard_api.companies')),
            ],
        ),
    ]
