# Generated by Django 4.0.3 on 2022-03-17 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_api', '0010_riskmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskmodel',
            name='filing_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
