# Generated by Django 4.0.3 on 2022-03-17 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_api', '0011_alter_riskmodel_filing_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentimentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filing_date', models.DateField(blank=True, max_length=100, null=True)),
                ('confidence', models.FloatField(blank=True, max_length=100)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('positive', models.CharField(blank=True, max_length=1000)),
                ('negative', models.JSONField(blank=True, max_length=1000)),
                ('type', models.CharField(blank=True, max_length=100)),
                ('company', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard_api.companies')),
            ],
        ),
    ]
