# Generated by Django 3.2 on 2022-03-17 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_api', '0012_sentimentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentimentmodel',
            name='item',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='sentimentmodel',
            name='negative',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
