# Generated by Django 3.2 on 2022-03-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_api', '0013_auto_20220317_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='derivedmetrics',
            name='sentence',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
